# Generated by Django 4.2.16 on 2024-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('host', models.CharField(choices=[('Coding Club', 'Coding Club'), ('Music Club', 'Music Club'), ('Drama Club', 'Drama Club'), ('Sports Club', 'Sports Club'), ('Photography Club', 'Photography Club'), ('Literature Club', 'Literature Club'), ('Art Club', 'Art Club'), ('Environment Club', 'Environment Club'), ('Robotics Club', 'Robotics Club'), ('Science Club', 'Science Club')], max_length=50)),
                ('type', models.CharField(choices=[('Event', 'Event'), ('Workshop', 'Workshop')], max_length=50)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('registration_link', models.URLField(max_length=500)),
            ],
        ),
    ]
