# Generated by Django 4.2.17 on 2025-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Event', 'Event')], max_length=50),
        ),
    ]
