# Generated by Django 5.1.4 on 2025-01-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='imageTwo',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(choices=[('Coding Club', 'Coding Club'), ('Music Club', 'Music Club'), ('Drama Club', 'Drama Club'), ('Sports Club', 'Sports Club'), ('Photography Club', 'Photography Club'), ('Literature Club', 'Literature Club'), ('Art Club', 'Art Club'), ('Environment Club', 'Environment Club'), ('Robotics Club', 'Robotics Club'), ('Science Club', 'Science Club')], max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=2555, null=True),
        ),
    ]
