# Generated by Django 5.1.4 on 2025-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
