# Generated by Django 4.2.17 on 2025-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(choices=[('Association of Mechanical Engineering', 'AMES'), ('Compuatiional Mathematics Club', 'KUCMC'), ('Forum for Environmental Conservation and Management', 'FECAM'), ('Forum of Pharmacy', 'FoP'), ('Kathmandu University Architecture Students Club', 'KUARC'), ('Geomatics Engineering Society', 'GES'), ('Kathmandu University Circle of Noble Chemineers', 'KUCONC'), ('Kathmandu University Civil Engineering Club', 'KUCEC'), ('Kathmandu University Computer Club', 'KUCC'), ('Natural and Social Concern Society', 'NSCS')], max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=2555),
        ),
    ]
