# Generated by Django 5.1.4 on 2025-01-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_clubs_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
            options={
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
