# Generated by Django 5.1.4 on 2025-02-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(choices=[('Kathmandu University Computer Club', 'KUCC'), ('Association of Mechanical Engineering', 'AMES'), ('Compuatiional Mathematics Club', 'KUCMC'), ('Forum for Environmental Conservation and Management', 'FECAM'), ('Forum of Pharmacy', 'FoP'), ('Kathmandu University Architecture Students Club', 'KUARC'), ('Geomatics Engineering Society', 'GES'), ('Kathmandu University Circle of Noble Chemineers', 'KUCONC'), ('Kathmandu University Civil Engineering Club', 'KUCEC'), ('Kathmandu University Computer Club', 'KUCC'), ('Natural and Social Concern Society', 'NSCS'), ('Kathmandu University Robotics Club', 'KURC'), ('Biotechnology Creatives', 'KUBIC'), ('Society of Electrical and Electronic Engineers', 'SEEE'), ('Society of business Information Student', 'SBIS'), ('Artificial Intellengence Club', 'KUAIC'), ('Kathmandu University Indoors Games Club', 'KUGIC'), ('Kathmandu University Society of Music and Clulture', 'KUSMC')], max_length=500),
        ),
    ]
