# Generated by Django 5.1.4 on 2025-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_event_description_event_image_url_event_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image_url',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
