# Generated by Django 5.1.4 on 2025-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_subscriber_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('event', 'event'), ('workshop', 'workshop')], max_length=50),
        ),
    ]
