# Generated by Django 5.1.4 on 2025-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_event_image_alter_event_registration_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
