# Generated by Django 5.1.4 on 2025-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_event_created_by_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
