# Generated by Django 5.1.4 on 2025-01-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_rename_time_event_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
    ]
