# Generated by Django 5.1.4 on 2025-01-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_event_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='startTime',
        ),
    ]
