# Generated by Django 5.1.4 on 2025-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_event_created_by_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(blank=True, choices=[('KUCC', 'Kathmandu University Computer Club'), ('KUARC', 'Kathmandu University Architecture Students Club'), ('KURC', 'Kathmandu University Robotics Club'), ('KUCEC', 'Kathmandu University Civil Engineering Club'), ('SEEE', 'Society of Electrical and Electronic Engineers'), ('KUSMC', 'Kathmandu University Society of Music and Clulture'), ('AMES', 'Association of Mechanical Engineering'), ('KUCMC', 'Compuatiional Mathematics Club'), ('FECAM', 'Forum for Environmental Conservation and Management'), ('FoP', 'Forum of Pharmacy'), ('GES', 'Geomatics Engineering Society'), ('KUCONC', 'Kathmandu University Circle of Noble Chemineers'), ('NSCS', 'Natural and Social Concern Society'), ('KUBIC', 'Biotechnology Creatives'), ('SBIS', 'Society of business Information Student'), ('KUAIC', 'Artificial Intellengence Club'), ('KUGIC', 'Kathmandu University Indoors Games Club')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
