# Generated by Django 5.1.4 on 2025-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_remove_event_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
