# Generated by Django 5.1.4 on 2025-02-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_delete_eventregistration'),
        ('Api', '0007_event_created_by_alter_user_username'),
    ]

    operations = [
    ]
