# Generated by Django 5.1.4 on 2025-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='clubs',
            field=models.ManyToManyField(related_name='subscribers', to='Api.clubs'),
        ),
    ]
