import { Button } from "@/components/ui/button"
import { Icons } from "./components/icons"
import { ArrowRight } from "lucide-react"
import Footer from "./components/footer/Footer"
import Searchbar from "./components/SearchBar/searchbar"
import Navbar from "./components/Navbar/Navbar"
export default function Home() {
  return (
    <div className="flex flex-col min-h-screen mt-[60px]">
      <main className="flex-grow">
        <Navbar />
        <text>

          American Writers is a work of literary criticism by American writer and critic John Neal. Published by Blackwood's Edinburgh Magazine in five installments between September 1824 and February 1825, it is recognized by scholars as the first history of American literature and the first substantial work of literary criticism concerning US authors. It is Neal's longest critical work and at least 120 authors are covered, based entirely on Neal's memory. With no notes or books for reference, Neal made multiple factually inaccurate claims and provided coverage of many authors that modern scholars criticize as disproportionate to their role in American literature. Scholars nevertheless praise the staying power of Neal's opinions, many of which are reflected by other critics decades later, notably "Fenimore Cooper's Literary Offenses" by Mark Twain. Theories of poetry and prose in American Writers foreshadowed and likely influenced later works by Edgar Allan Poe and Walt Whitman. In an early critique of the colonial mentality and call for literary decolonisation, Neal argued American literature relied too much on British precedent and had failed to develop its own voice. He offered sharp criticism of many authors while simultaneously urging critics not to offer writers from the US undeserved praise, lest doing so stifle the development of a truly distinct American literature. Poe's later critical essays on literature reflected these strictures.

          Neal wrote the series in London, where he lived between 1824 and 1827. Having moved there from Baltimore, his goals were to establish himself as America's leading literary figure, encourage the development of a uniquely American writing style, and reverse British disdain for literature from the US. He soon became the first American published in any British literary journal, American Writers being the longest and best-remembered of his works on American topics in multiple UK periodicals. He wrote for Scottish publisher William Blackwood under an English pseudonym, which Neal assumed was convincing. Blackwood and British readers likely realized they were reading the work of an American, and multiple leading American periodicals outed Neal before the series was completed.

          The series was well received in the UK and exerted influence over British critics, some of whom repeated Neal's analyses and misinformation into their own essays without investigating for themselves. It conversely drew considerable ire from US journalists, none more severe than William Lloyd Garrison, who warned Neal to be on guard should he return to his home country. When he did, Neal found inflammatory broadsides and in-person hostility in his hometown of Portland, Maine, leading to a fistfight. In defiance, he decided to stay in Portland, where he lived until his death forty-nine years later. The first postmortem republication of a substantial work by Neal was 1937, when Fred Lewis Pattee collected American Writers for the first time into one publication. That 1937 edition remains the most accessible of Neal's literary productions.

          Background
          Blackwood engages Neal
          Color oil painting of a young white man with light brown short wavy hair and a plain countenance
          John Neal c. 1823, by Sarah Miriam Peale
          After eight years in Baltimore, John Neal sailed to England in late 1823.[1] He pursued three primary goals: supersede Washington Irving and James Fenimore Cooper as the leading US literary figure, usher into existence a new uniquely American literary style, and reverse British disdain for American literature.[2] To accomplish the third goal, Neal sought publication in British literary journals to expose UK readers to writing from the US and convince them of its value.[3] A "man of grievances" according to English scholar George L. Nesbitt,[4] Neal envisioned those journals as a "blazing rocket-battery" he could turn to fire upon the readership of "swarming whipper-snappers" in Great Britain.[5] Thinking highly of his own abilities, he was confident he would fast become a leading literary figure in London.[6]

          Color painting of a seated white man with white hair, wearing a black jacket over a white shirt
          William Blackwood c. 1830
          Neal's resources were running low after three months in England with no income. Capitalizing on Europeans' interest in US politics sparked by recent news of the Monroe Doctrine, he wrote an article on the five US presidents and current presidential candidates and submitted it to Blackwood's Edinburgh Magazine.[7] His letter said he was about to leave London to explore Europe, but: "In the mean time, I must have some sort of employment to keep me out of mischief."[8] Biographer Donald A. Sears says "the situation was desperate" when Neal received a response from Scottish publisher William Blackwood:[7] "You are exactly the correspondent that we want".[9] The payment of five guineas[a] was more than Neal had ever received for any magazine submission.[14]

          Early American literature scholar William B. Cairns considered Blackwood's the most important literary periodical in 1820s Great Britain, a period when such periodicals were more influential than ever before.[15] Neal was already familiar with it and had read it in Baltimore.[16] The editors of a six-volume 2016 academic collection of Blackwood's articles called it "the most brilliant, troubling, acerbic and imaginative periodical of the post-Napoleonic age".[17] Literature scholar Fritz Fleischmann described the magazine as subscribing to an "aesthetic belief in original thoughts expressed in bold and forceful language".[18] The editor of a 1959 academic Blackwood's collection used the words "riotous" and "blackguardly".[19] The magazine did not, however, publish a single piece on an American topic from June 1822 until Neal's first piece in May 1824.[20]

          Neal felt he was a good fit for Blackwood's, having sought it out as "the cleverest, the sauciest, and most unprincipled of our calumniators", he later wrote.[21] Cairns agreed, writing: "Neal's slashing style and the somewhat sensational nature of his utterances fitted well with the manner of Blackwood's".[22] Blackwood seemed to enjoy Neal's style and wanted it in his magazine.[23] Neal was one of many new contributors adopted by Blackwood in the early 1820s; alongside Eyre Evans Crowe, he was one of two to exhibit the publisher's desired style notably well.[24] Neal's article in the May 1824 issue was the first by an American to appear in any British literary journal,[25] and it was soon republished by the New European in multiple languages throughout mainland Europe.[26]

          Steady contributorship
          During his three years in England, Neal contributed articles to eight other British periodicals, including The European Magazine, The London Magazine, Monthly Magazine, The New Monthly Magazine, and The Westminster Review.[27] He had an article in the European Review's inaugural (June 1824) issue, and editor Alexander Walker paid more than Blackwood, but Walker also rejected all of Neal's subsequent submissions after learning Neal was American.[28] Neal sent five more articles to Blackwood with a letter explaining his willingness to cover any manner of topics; Blackwood rejected them all.[29] His sixth submission to Blackwood was accepted,[30] and Neal became a regular contributor, finding himself "warmly welcomed and handsomely paid", according to Sears.[7] As the magazine's first major American contributor,[24] Neal authored at least one article for every issue between May 1824 and February 1825.[31] Neal's presence in its pages was substantial enough that literary historian Fred Lewis Pattee called it a "complete surrender" on the part of "Blackwood's to the swashbuckling young American".[32]

          Neal later wrote that he traveled to the UK on a mission to write about American topics, but biographer Irving T. Richards argues Neal more likely settled into that pattern after connecting with Blackwood.[33] Either way, he quickly became Blackwood's primary authority on US topics.[34] This series of articles highlighted cultural similarities between the US and UK, making the case for an improved transatlantic relationship.[35] It served to counterpoise ample content from contemporary UK authors that predominantly disparaged the US, when it considered the new nation at all.[36] A decade later, Neal called Blackwood's "the first British Magazine that ever allowed an American fair play".[37] He further claimed Blackwood "published for me what no other magazine-proprietor in the three kingdoms would have dared to publish".[38]

          The first installment of the American Writers series was published in the September 1824 issue.[39] Before publishing the second installment, Blackwood requested some changes, particularly that Neal tone down his attack on John Elihu Hall and refrain from calling him a blackguard.[40] After publishing the last installment in February 1825, Blackwood sent Neal a letter congratulating him on completing the series. He encouraged standalone articles in the future, but to continue on American topics.[41] Neal did not publish anything else substantial in Blackwood's until September, however.[42]

          Anonymity
          Neal was convinced that anything submitted by an American to any British periodical would be rejected if it did not disparage the US.[5] For his writing to be accepted, "Neal treated the venture as an undercover operation", according to literature scholar Ellen Bufford Welch.[43] Pattee said, "he considered [it] an impenetrable disguise".[38] Neal started by introducing himself as Carter Holmes in his first communication with Blackwood,[44] and continued using the pseudonym in all correspondence with him while writing American Writers.[45] He made clear it was a pseudonym, but maintained he was English.[44] Scholars believe Blackwood and his editors figured out quickly they were dealing with an American.[46]

          The American Writers series appeared in Blackwood's under the initials X.Y.Z.,[47] which Neal borrowed from fellow contributors John Wilson and John Gibson Lockhart.[48] He used other names for other Blackwood's pieces.[49] Despite describing himself in those pages as English, Cairns and Pattee believe most British readers knew they were reading the work of an American.[50] Likely reflecting British readership in general, The Westminster Review stated years later in 1831: "There is no mistaking the hand of John Neal" in his work published in British periodicals.[51]

          US readers also largely knew American Writers was the work of an American,[52] and many connected the series to Neal.[53] Based on his reading of the first two installments, Philadelphian John Elihu Hall outed Neal as author in The Port Folio in late 1824.[54] The United States Literary Gazette followed suit the following May.[55] When reviewing his own work in American Writers, Neal hinted at his identity, saying, "we know him well" and describing his anonymously-published novels: "No matter whose they are—mine or another's ... I shall neither acknowledge, nor deny them."[56] In his last piece for Blackwood's, published after the final installment of American Writers, Neal proclaimed his true nationality and signed it with his last initial.[57] He revealed his name to Blackwood in a letter around the same time.[44] The protagonist of Neal's 1830 novel Authorship was named Carter Holmes,[58] which the book called a "fictitious name" connected to "Blackwood".[59]

          Content
          Black letters on white paper and the bust of an older bearded white man in a dark coat surrounded by thistles
          Blackwood's volume 16
          American Writers comprises about 50,000 words[35] over 80 magazine pages.[60] Literature scholars Alfred Fiorelli, Benjamin Lease, and Hans-Joachim Lang counted 120 names among the authors covered by Neal.[61] Both biographer Irving T. Richards and scholar Alberta Fabris put the number at 135.[62] Those figures, both living and dead at the time, included novelists, poets, political writers, scientific writers, philosophers, theologians, journalists, historians, geographers, and even painters.[63] Each figure is covered with at least a paragraph, though some get multiple pages.[64] Richards said the coverage of each writer "frequently grossly violated" their comparative importance, such as the half page on James Fenimore Cooper, six pages on Charles Brockden Brown, eight on himself, and ten on Washington Irving.[65]

          Aside from familiarizing British readers with American authors,[66] Neal's central message in American Writers is that the US had not yet developed its own voice:[67] there is "no such thing in the United States of North America, as a body of native literature ... bearing any sort of national character."[68] He offered specific recommendations for bringing one about by encouraging natural originality over studied adherence to established models.[69] He said: "If you go in your natural shape, in the true garb of your nation, you will never be laughed at."[70] Neal also advised literary critics to give US writers more attention, but to avoid undeserved praise, for fear it would stifle creative growth.[71] "Let us never make a prodigious fuss about any American book, which if it were English, would produce little or no sensation ... it is only insulting the Americans", he said.[72] Following his own advice, his assessment of individual writers was "brutally honest", according to Welch.[73] Where he did find what he considered truly American literature, he named only Brown, himself, and James Kirke Paulding.[74]

          He wrote about all authors from recollection, having brought neither any of their works nor any notes on them from America. As a result, Neal devoted more space in some cases to anecdotes he could remember about an author than to analysis of their work. According to the editors of a 2016 collection of Blackwood's articles: "The series is notoriously riddled with factual errors".[35] He wrote it all in a conversational tone unique to himself, despite external pressures to adhere to established models.[75] That style was nevertheless more controlled than his other work to maintain his English pseudonym.[76] Literature scholars Edward Watts and David J. Carlson contended the series foreshadowed a clash on the literary horizon between genteel traditions and popular vulgarity in Anglophone literature.[45]

          Neal critiqued his own works and included a short biography of himself in American Writers.[47] Richards considered that coverage to be far out of proportion to his role in American literature.[65] Literature scholar Jonathan Elmer called it "brazen".[47] The coverage offers mixed reviews, saying of himself "he overdoes everything" in his novels, "hardly one of which it is possible to read through."[77] He nevertheless judged Seventy-Six to be "one of the best romances of the age".[78] Logan "is full of power—eloquence—poetry—instinct" but still "so outrageously overdone, that no-body can read it through."[79] Lease and Cairns considered Neal's coverage of Cooper to be disproportionately brief.[80] In it, he dismissed Cooper's female characters as "nice, tidy, pretty—behaved women, who ... talk very much like a book".[81] Neal summed him up as "a man of sober talent—nothing more."[82] Seven decades later, Mark Twain struck a very similar tone in his own essay, "Fenimore Cooper's Literary Offenses".[83] Neal also included a discussion of John Dunn Hunter, which was based to a degree on their time in the same London boarding house. That section is a largely accurate prediction of Hunter's future reputation as an untrustworthy imposter and filibuster.[84] Neal's critique of William Cullen Bryant was likely the basis for the section on Bryant in James Russell Lowell's satirical poem A Fable for Critics over twenty years later.[85]

          Contemporary reactions
          United Kingdom
          American Writers exerted influence over British periodicals and the way they treated literature from the US;[86] many used quotes from the series to substantiate their own work,[87] including multiple instances of misinformation unwittingly copied from Neal.[88] For instance, the Quarterly Review's March 1825 review of Irving was presumably copied from Blackwood's, rather than based on an original interpretation.[89] Being published in a respected journal likely convinced British readers of American Writers's validity.[88] The British Critic in April 1826 said Neal's novels were too extreme, but praised American Writers, saying it "shows him to be well worth the trouble of breaking in".[90] Cairns credits Neal's coverage of himself with ushering a brief period of increased critical attention to his novels among British reviewers.[91]

          Blackwood's contributor David Macbeth Moir called American Writers the best assessment of US literature yet published, praising "its knowledge of a subject concerning which we sit in darkness."[92] Conversely, fellow contributor William Maginn wrote to Blackwood, attacking the series as "a tissue of lies from beginning to end".[93] Citing the broadly positive feedback he had already received from his readership, Blackwood responded, "there are not manny [sic] articles I have had which have done so much for [Blackwood's] as these of this writer."[94] To Neal, he wrote after the last installment: "You have finished your series in capital style. The whole is spirited and most original."[95]

          United States
          Neal had written five novels in Baltimore and published extensively in periodicals throughout the US before moving to London, but by mid-1825, American readers generally associated his name with American Writers more than any of his previous works.[96] At the same time, the reception there was much worse than in the UK.[97] American readers were generally offended by Neal's sharp criticism,[98] particularly because he wrote and published it in a country with which they had been at war twice in the previous half century.[99] Neal expected this reaction and was aware of it before he returned to the US.[100] His friend Tobias Watkins in Baltimore wrote him in July 1825 to inform him of the poor reaction from American journalists, including many with whom Neal had associated before leaving Baltimore.[101] Years later he wrote, "the whole paperhood of America, were baiting and badgering me, at every turn, ... because, forsooth, in dealing with our American authors, ... I had told the truth of them."[102]

          Theophilus Parsons, called a "blockhead" by Neal in American Writers, wrote in the United States Literary Gazette for May 1825 that Neal's authorship rendered the series invalid.[103] Joseph T. Buckingham called it an "unnatural" and "unprincipled" attack on Neal's country.[104] Hall in the Port Folio called Neal a "slimy reptile" and "impudent scribbler", suggesting controversy drove him from Baltimore to London "where he earns his crust by defaming his native land", such that he "should be spit upon or cowskinned".[105] After reading the installment of American Writers that mentions him, Hall called Neal "a liar of the first magnitude" and a "nauseous reptile".[106] A New York critic said Blackwood's Magazine's value had "sadly fallen off when a man who could not find a reader in America, goes to England, and ranks first quill."[107] The Boston Commercial Gazette, reacting to the series's first installment, called Neal "a half educated, half crazy headed author" who was "kicked from every city in the United States" to "escape to England, to sell their venom, froth, and lies, to mercenary journalists."[108] Hezekiah Niles, who briefly employed Neal in Baltimore,[109] referred to Neal as "some fool" and a "renegado" in the Weekly Register, suggesting American Writers was published to intimidate America's developing literary community.[110] The most severe reaction came from William Lloyd Garrison,[111] whose May 1825 reaction to American Writers was Garrison's most substantial contribution to the Newburyport Herald, whereat he was apprenticing.[112] He said: "We cannot express sufficiently, our Indignation at this renegade's base attempt to assassinate the reputation of this country",[113] warning Neal to be on guard should he return to the US, "or you may reap that reward for your vile labors, which you so richly merit."[114] This was the beginning of a feud between the two men that continued for years.[111] Speaking for the minority of US literary figures who favored Neal's piece in Blackwood's, Sumner Lincoln Fairfield in the New York Literary Gazette in April 1826 said Neal "has really and truly done much service to his country ...; his treatment in America was cruel and abominable".[115]

          Portland, Maine
          Black letters on white paper
          Broadside posted in Portland, Maine, in 1827
          Neal left England and returned to his hometown of Portland, Maine, in July 1827,[116] probably expecting the ire sparked by his British publications to have died down and for a warm welcome to be in its place.[117] He instead found hostility in Portland to be greater than the nation as a whole.[118] Many still resented him for not only American Writers and his Blackwood and Sons–published novel Brother Jonathan (1825), but his 1823 Baltimore novels Randolph and Errata, the latter of which being a semi-autobiographical story that disparaged well-respected locals.[119] Pattee summarized: "For a time he felt like a man without a country".[120] He was accosted on the street by locals waiting for him on the stoop of a tavern. The confrontation led to a fistfight in which the group's leader left with a bloody nose.[121] Neal also found broadsides posted throughout the city sarcastically proclaiming his writing in London and Baltimore had driven him insane and he was recovering with help from an "African Physician", who was in actuality a local Black man hired by the broadside's authors to follow him in public.[122] Neal allowed the man to follow until Neal's detractors could no longer afford to pay him to continue.[123] Neal had not planned on staying in Portland, but changed his mind in defiance of the opposition to his return.[124] He stayed in Portland until his death forty-nine years later.[99]

          Influence on American writers
          Along with Neal's essays on drama in The Yankee and the preface to his poem The Battle of Niagara (1818), American Writers was likely a primary influence on Edgar Allan Poe's theory of poetry.[125] Poe's own involvement with Blackwood's supports this theory among scholars.[126] Neal said: "The day is rapidly approaching, when the poetry of conventional meter must give way to a mightier poetry in prose."[127] Neal's theory "boldly prophesies the organicism of" Ralph Waldo Emerson and Walt Whitman, according to Lease,[128] and probably had a direct influence on Whitman, according to literature scholar Joseph Jay Rubin.[129] Neal's pleas not to stifle US literature by fluffing undeserving American writers likely influenced Poe's critical essays, which contained similar language.[130] Neal's criticism of Harriet Vaughan Cheney's A Peep at the Pilgrims in 1636 (1824) contended the book did a great job of presenting dry history while failing to communicate the spirit of the experience. This analysis probably influenced Nathaniel Hawthorne's similar take on Views and Reviews in American History by William Gilmore Simms (1845) two decades later.[131] By claiming the US did not yet have a distinct literature, Neal made it possible for authors of the later American Renaissance to feel justified in disregarding a half century of American precedent and thinking themselves the first in their country's history.[132]

          Scholarship
          Scholars have called American Writers the first history of US literature[133] and the first substantial criticism of American literature.[134] Some contend it is the work for which Neal is best known,[135] at least among his British publications,[136] or for that period of his life.[137] Of all Neal's works of literary criticism, it is the most extensive,[138] and according to literature scholar Abbate Badin, his most interesting to a modern audience.[139] Fleischmann called it "an unprecedented success" in terms of educating British readership.[140]

          Pattee acknowledged Neal's misinformation and unfair attacks,[141] but otherwise judged the work as "sound criticism"[75] and praised the staying power of Neal's critiques, saying, "his critical judgments have held. Where he condemned, Time has almost without exception condemned also."[85] Literature scholar Alexander Cowie issued a similarly balanced assessment, concluding that American Writers is "generally rich in acute critical perceptions".[142] This was also echoed by Sears,[143] Lease,[144] and the editors of a 21st-century collection of Blackwood's articles, who pointed to "caustic one-liners or generic praise" Neal used for works with which he was less familiar but "cogent, authoritative and lucid" comments for his favorite works.[35] An example of Neal's misinformation and unfairness was captured by the 1930 biographer of Fitz-Greene Halleck, who referred to Neal's critique of Halleck as "difficult to match for hopeless inaccuracy and unabashed egotism."[145] Richards summarized American Writers as "altogether honest, reasonably just, and exceedingly shrewd in its judgments."[65] Richards contended a century after American Writers that scholars generally still agreed with Neal's assessment of many of the authors the piece considers, particularly Bryant and Irving.[146] The introduction to the 1927 edition of Irving's A History of New York claimed Neal's to be "the most intelligent review" of that work since its publication in 1809.[147]

          Publication history
          Referred to by Neal as a book,[148] American Writers was originally published as five successively-numbered installments between September 1824 and February 1825.[35] Their first collection in one publication was American Writers: A Series of Papers Contributed to Blackwood's Magazine (1824–1825), edited by Fred Lewis Pattee in 1937.[149] That edition includes "Late American Books", an essay originally published in Blackwood's in September 1825.[150] Scholar Robert Bain considered that piece the sixth installment of American Writers.[151]

          The 1937 edition also includes a bibliography of Neal's other works and excerpts from his 1823 novel Randolph.[150] Randolph includes what Pattee and Badin considered a more interesting version of Neal's ability to produce a series of sketches of American figures,[152] which is why Pattee decided to include the excerpt.[153] This was the first republication of a substantial work by Neal since his death. It was also the first of a series in the twentieth century that included Observations on American Art: Selections from the Writings of John Neal in 1943, "Critical Essays and Stories by John Neal" in 1962, Rachel Dyer in 1964, Seventy-Six in 1971, and The Genius of John Neal in 1978,[149] the last of which includes Neal's review of Irving from American Writers and his review of Cooper from "Late American Books".[154] Of those, Pattee's collection
        </text>
      </main>
      <Footer />
    </div>

  )
}
